# Generated by Django 5.2.7 on 2025-11-22 08:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0004_partner_alter_operation_partner_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='lowstockalert',
            name='is_read',
            field=models.BooleanField(default=False),
        ),
    ]
